---
# SPDX-License-Identifier: EUPL-1.2
# SPDX-FileCopyrightText: 2026-present Jürgen Mülbert <juergen.muelbert@gmail.com>

version: "3"

# ====================================================================
# CONFIGURATION
# ====================================================================
# -----------------------------------------------------------
# 🧩 GLOBALS
# -----------------------------------------------------------
vars:
  LOG: warn
  DOMAIN: jm-github-standards
  BASE_URL: https://jmuelbert.github.io/{{ .DOMAIN }}/
  SRC_DIR: scripts
  DOCS_DIR: docs

tasks:
  # ====================================================================
  # 🪵 INTERNAL HELPERS
  # ====================================================================
  _log:
    internal: true
    silent: true
    # TYPE: info, success, warn, error
    vars:
      SYMBOL:
        sh: |
          case "{{.TYPE}}" in
            info) echo "ℹ️" ;;
            success) echo "✅" ;;
            warn) echo "⚠️" ;;
            error) echo "❌" ;;
            *) echo "" ;;
          esac
    cmds:
      - echo "{{.SYMBOL}} [{{.TYPE | upper}}] {{.MSG}}"

  # ====================================================================
  # 1. SETUP & ENVIRONMENT
  # ====================================================================
  setup:
    desc: "Complete project setup: uv (Python), pnpm (Node), Lefthook & REUSE"
    cmds:
      - task: _log
        vars: { MSG: Initializing development environment..., TYPE: info }
      - uv sync --extra dev
      # - go mod download
      - pnpm self-update
      - pnpm install
      - pnpm dlx lefthook install
      - uv run reuse download --all
      - uv run vale sync
      - task: _log
        vars: { MSG: ✅ Setup complete. All dependencies installed and Git-Hooks active!, TYPE: success }

  maintenance:update-all:
    desc: Updates all dependencies (pnpm, uv, lefthook) and licenses
    cmds:
      - pnpm update --latest
      - uv lock --upgrade
      - uv run reuse download --all
      - task: lint
      - task: _log
        vars: { MSG: Project dependencies and compliance updated., TYPE: success }

  clean:
    desc: Clean all transient files and caches
    cmds:
      - task: _log
        vars: { MSG: "🧹 Cleaning caches, builds, and translation files...", TYPE: info }
      - rm -rf dist build site .cache .venv uv.lock .tmp/ node_modules/
      - task: _log
        vars: { MSG: 🧹 All cleaned, TYPE: success }

  # ====================================================================
  # 2. QUALITY CONTROL (LINT & FORMAT)
  # ====================================================================
  lint:
    desc: Run all linting
    cmds:
      - task: _log
        vars: { MSG: 🧪 Linting all..., TYPE: info }
      - task: lint:standards
      - task: lint:yaml
      - task: lint:toml
      - task: lint:docs
      - task: lint:commit
      - task: _log
        vars: { MSG: ✅ All linting complete., TYPE: success }

  lint:standards:
    internal: true
    cmds:
      - task: _log
        vars: { MSG: 🧪 Checking REUSE compliance & GitHub Actions..., TYPE: info }
      - uv run reuse lint
      - go run github.com/rhysd/actionlint/cmd/actionlint@latest .github/workflows/*.yml
      - pnpm run lint
      - task: _log
        vars: { MSG: ✅ linting standards complete., TYPE: success }

  lint:yaml:
    desc: Runs yamllint to check all YAML files.
    cmds:
      - task: _log
        vars: { MSG: 🧪 Running yaml linting..., TYPE: info }
      - uv run yamllint -c .yamllint.yml .
      - task: _log
        vars: { MSG: ✅ yaml linting complete., TYPE: success }

  lint:commit:
    desc: Validate the last commit message for SemVer compliance
    cmds:
      - task: _log
        vars: { MSG: 🧪 Running commit linting..., TYPE: info }
      - pnpm exec commitlint --from HEAD~1 --to HEAD --verbose
      - task: _log
        vars: { MSG: ✅ commit linting complete., TYPE: success }

  lint:links:
    desc: Validate markdown links via pnpm script
    cmds:
      - task: _log
        vars: { MSG: 🧪 Running links linting..., TYPE: info }
      - pnpm run lint:links
      - task: _log
        vars: { MSG: ✅ links linting complete., TYPE: success }

  lint:toml:
    desc: Validate toml-files via taplo
    cmds:
      - task: _log
        vars: { MSG: 🧪 Running toml-linting..., TYPE: info }
      - uv run taplo lint
      - task: _log
        vars: { MSG: ✅ toml linting complete., TYPE: success }
    preconditions:
      - sh: uv pip show taplo || command -v taplo
        msg: ❌ Taplo not found. Install it with 'uv pip add taplo'.

  lint:docs:
    desc: Lint general repository documentation (README, CONTRIBUTING, etc.)
    cmds:
      - task: _log
        vars: { MSG: ✍️ Checking general documentation, TYPE: info }
      - task: _log
        vars: { MSG: 🔍 Checking repository links..., TYPE: info }
      - pnpm run lint:links
      - task: _log
        vars: { MSG: ✍️ Checking the spelling, TYPE: info }
      - pnpm run lint:spell
      - task: _log
        vars: { MSG: ✍️ Checking general documentation with Vale..., TYPE: info }
        # yamllint disable-line rule:line-length
      - uv run vale "$PWD/README.md" "$PWD/.github/CONTRIBUTING.md" "$PWD/.github/CODE_OF_CONDUCT.md"
      # yamllint enable
      - task: _log
        vars: { MSG: ✅ linting docs complete., TYPE: success }

  format:toml:
    desc: Format toml-files via taplo
    cmds:
      - task: _log
        vars: { MSG: 🎨 Running toml-formatter..., TYPE: info }
      - uv run taplo format
      - task: _log
        vars: { MSG: ✅ toml formatting complete., TYPE: success }
    preconditions:
      - sh: uv pip show taplo || command -v taplo
        msg: ❌ Taplo not found. Install it with 'uv pip add taplo'.

  format:
    desc: Format code and docs
    cmds:
      - task: _log
        vars: { MSG: 🎨 Running formatters..., TYPE: info }
      - pnpm run format
      - task format:toml
      - task: _log
        vars: { MSG: ✅ formatting complete., TYPE: success }

  # ====================================================================
  # 3. DOCUMENTATION & LINKS
  # ====================================================================
  docs:lint:
    desc: Check Markdown links (Local MDs via Node, Docs via MkDocs)
    cmds:
      - task: _log
        vars: { MSG: 📚 Checking documentation integrity..., TYPE: info }
      - uv run -m linkcheckmd ./docs
      - uv run mkdocs build --clean --strict
      - task: _log
        vars: { MSG: ✍️ Checking the spelling, TYPE: info }
      - pnpm run lint:spell-docs
      - task: _log
        vars: { MSG: ✍️ Checking /docs prose with Vale..., TYPE: info }
      - uv run vale "$PWD/docs"
      - task: _log
        vars: { MSG: ✅ docs linting complete., TYPE: success }

  docs:serve:
    desc: Preview documentation locally
    cmds:
      - task: _log
        vars: { MSG: 🌐 Serving documentation..., TYPE: info }
      - uv run mkdocs serve --dev-addr localhost:8090
      - task: _log
        vars: { MSG: ✅ docs serving complete., TYPE: success }

  docs:build:
    desc: Build production documentation
    deps: [docs:lint]
    cmds:
      - task: _log
        vars: { MSG: 📘 Building documentation..., TYPE: info }
      - uv run mkdocs build --clean --strict
      - uv run python -m json.tool --sort-keys --no-indent
        ./site/search/search_index.json ./site/search/search_index.json

  fix:reuse:
    desc: Add license headers to source files
    cmds:
      # yamllint disable-line rule:line-length
      - uv run reuse annotate --license EUPL-1.2 --copyright "Jürgen Mülbert <juergen.muelbert@gmail.com>" {{.SRC_DIR}}/**/*
      # yamllint enable

  # ====================================================================
  # 4. HEAVY LINTING (Docker)
  # ====================================================================
  megalinter:
    desc: Run all static code analysis via MegaLinter Docker image.
    cmds:
      - task: _log
        vars: { MSG: 🐳 Starting MegaLinter analysis via Docker..., TYPE: info }
      - |
        rm -rf megalinter-reports
        docker run --rm \
          -v "$(pwd)":/tmp/lint \
          -e DISABLE_ERRORS_ON_LINTER="none" \
          -e JSON_REPORTER=false \
          -e SHOW_ELAPSED_TIME=true \
          -e VALIDATE_ALL_CODEBASE=true \
          -e MEGALINTER_CONFIG=/.github/config/.mega-linter.yml \
          -e APPLY_FIXES=true \
          oxsecurity/megalinter:latest
      - task: _log
        vars: { MSG: ✅ MegaLinter scan complete., TYPE: success }
